package com.hius74.words.data_source;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

@Entity(tableName = "cards", indices = {
        @Index(value = {"next_time", "stage"})
})
public class Card {

    /**
     * Required for room library update operation.
     * value 0 treated as autogenerate a new value.
     * Room return long as autogenerated field
     */
    @PrimaryKey(autoGenerate = true)
    public long id;

    /**
     * Front side of the card.
     */
    @ColumnInfo(name = "front_side")
    public String frontSide;

    /**
     * Back side of the card.
     */
    @ColumnInfo(name = "back_side")
    public String backSide;

    /**
     * Correct answer
     */
    @ColumnInfo(name = "answer")
    public String answer;

    /**
     * Next time to repeat the card.
     */
    @ColumnInfo(name = "next_time", index = true)
    public long nextTime;

    /**
     * Current stage of the learning process of the card.
     */
    @ColumnInfo(name = "stage")
    public int stage;

    /**
     * Parent Id for this card.
     * Used to make available to learn sentences after words learned.
     */
    @ColumnInfo(name = "parent_id")
    public long parentId;
}
